kind: pipeline
name: Docker Image Builder

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: greenbanana/docker-strava-backup
    auto_tag: true
    username: HUB_USERNAME
    password: HUB_PASSWORD
